on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[TEMPLATE 1] building..."
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[TEMPLATE 1] testing..."
